/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fancycinema;
 
import javafx.application.Application; 
import javafx.stage.Stage; 

import java.util.Map;

public class App extends Application {
    private Fancy userSystem;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        launch(args);
    }
    
    @Override 
    public void start(Stage primaryStage) {     
        Map<String, String> params = getParameters().getNamed(); 
        userSystem = new Fancy(primaryStage);
        primaryStage.setTitle("Fancy Cinema");
        primaryStage.setScene(userSystem.getScene());
        primaryStage.show(); 
        
    }
}
